services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env/.dev.env
    ports:
      - 8000:8000
    volumes:
      - ./api/src:/app
    depends_on:
      database:
        condition: service_healthy
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - .env/.dev.env
    ports:
    - 5173:5173
    volumes:
      - ./frontend:/app

  database:
    image: mysql:8.4.0
    env_file:
      - .env/.database.dev.env
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      interval: 3s
      retries: 10
