# Generated by Django 5.0.6 on 2024-06-20 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование типа')),
                ('serial_number_mask', models.CharField(max_length=255, verbose_name='Маска серийного номера')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'db_table': 'equipment_types',
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Серийный номер')),
                ('description', models.TextField(default='', verbose_name='Примечание')),
                ('archived', models.BooleanField(default=False, verbose_name='')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='api.equipmenttypemodel', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудования',
                'db_table': 'equipments',
            },
        ),
    ]
