# Generated by Django 5.0.6 on 2024-06-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_equipmentmodel_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipmentmodel',
            name='equipmentmodel_unique_serial_number',
        ),
    ]
