# Generated by Django 5.0.6 on 2024-06-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_equipmentmodel_equipmentmodel_unique_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
