FROM python:3.12.4-alpine3.20


ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VERSION=1.5.1

# Install poetry.
RUN pip install "poetry==$POETRY_VERSION"

# Copy only requirements to cache them in docker layer
WORKDIR /app

COPY poetry.lock pyproject.toml /app/

RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add --no-cache mariadb-dev


# Configurate poetry and install requirement dependencies.
RUN poetry config virtualenvs.create false && poetry install --no-dev --no-interaction --no-ansi

RUN apk del build-deps

# Copy project into container.
COPY src /app

CMD python manage.py migrate && python manage.py runserver "0.0.0.0:8000"